### ISSUE TITLE
Change Launch icon

### ISSUE THREAD

**Issue by euriconoleto** [gadenbuie/metathis#14]
I want to change my launch icon... but I don't know how to create a metatag for this line. Any idea?
<link rel="apple-touch-icon" sizes="40x40" href="triatlas.png">

**Comment by gadenbuie** [comment]
For icons I would recommend use a service like https://realfavicongenerator.net/ (used by [pkgdown](https://pkgdown.r-lib.org/reference/build_favicons.html)) to generate the correct images and markup, etc.

This service generates a bundle for you that you download and extract in your root folder, and then you can use the `includes` argument of `rmarkdown` outputs to include the HTML code they provide, e.g.

```yaml
# in your .Rmd
output:
  rmarkdown::html_document
    includes:
      in_header: favicon.html
```

```html
<!-- favicon.html -->

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```
