### ISSUE TITLE
Image not showing for summary_large_image

### ISSUE THREAD

**Issue by llrs** [gadenbuie/metathis#19]
Hi! Many thanks for providing this package and your post about how to share presentations.

I am following the guide and I have problems with the [slides](https://user2021.llrs.dev) I'm working with at the moment. 
The twitter card validator doesn't find [the image](https://llrs.dev/2020/07/bioconductor-submissions-reviews/index_files/figure-html/first_plot-1.png) for the summary_large_image:
![Screenshot from 2021-06-05 16-42-30](https://user-images.githubusercontent.com/6818218/120895404-198db280-c61d-11eb-83e2-4c7f94ffdf5a.png)

Only when I changed to `twitter_card_type = "summary"` it did show the image. Is there something that images of the summary card should have?

I checked on the [help page](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image) but besides not having the ratio (it has ratio 1344/960) it meets the other requirements:

> Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

**Comment by gadenbuie** [comment]
I'm seeing this now so maybe you fixed it? If not, I'd need a link to the source code or a reprex to diagnose.

![image](https://user-images.githubusercontent.com/5420529/120897240-141b7280-c5f3-11eb-9b23-cfc84731667c.png)

**Comment by llrs** [comment]
Thanks for the quick reply. I temporarily switched to summary instead of summary_large_image to at least have an image.

The repo is https://github.com/llrs/useR2021 an the code is on the second chunk on index.Rmd:

```r
library(metathis)
meta() %>%
  meta_name("github-repo" = "llrs/user2021") %>% 
  meta_social(
    title = "Reviewing packages; how does it work?",
    description = paste(
      "Analysis and tips about how package reviews work.",
      "Presented at useR!2021."
    ),
    url = "https://user2021.llrs.dev",
    image = "https://llrs.dev/2020/07/bioconductor-submissions-reviews/index_files/figure-html/first_plot-1.png",
    image_alt = paste(
      "Image from a blog https://llrs.dev/2020/07/bioconductor-submissions-reviews/ for Reviewing packages; how does it work?", 
      "Horizontal axis the date, vertical axis the submissions on Bioconductor each point is an event on a submission. It shows a continuous increase on packages submitted.", 
      "Presented at useR!2021 by Lluíss Revilla"
    ),
    og_type = "website",
    og_author = "Lluís Revilla",
    twitter_card_type = "summary_large_image", # Now it is using "summary"
    twitter_creator = "@Lluis_Revilla"
  )
```

**Comment by gadenbuie** [comment]
Ah, I found the problem. I was using `twitter:image:src` for the meta tag `name`, which used to work and most certainly came from an example on the Twitter docs. But the correct `name` property value should be `twitter:image`. I'll have a fix here shortly.

**Comment by llrs** [comment]
Great!! Many thanks

**Comment by gadenbuie** [comment]
No problem, glad I found the fix! (I'll close the issue when I merge the PR)
