### ISSUE TITLE
correcting link to MDN docs about viewport meta tag

### ISSUE THREAD

**Issue by IndrajeetPatil** [gadenbuie/metathis#25]
The link here says there is no content available:
https://github.com/gadenbuie/metathis/blob/f253ce2af2615ce86ba15b78123da926b18a6395/R/viewport.R#L6

I think it should be replaced with the following?
<https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag>

**Comment by gadenbuie** [comment]
Thanks! You're right, that's the intended link. I'm pretty sure the URL worked when I last submitted to CRAN 😬
