### ISSUE TITLE
Is metathis compatible with quarto?

### ISSUE THREAD

**Issue by shannonpileggi** [gadenbuie/metathis#28]
Is `metathis` compatible with quarto slides or websites? 

I am getting a hard to decipher error when I try to apply to quarto slides [here](https://github.com/shannonpileggi/introducing-gtreg-rmed-2022/blob/ca1b9e03c55b1dc2290e933393cd49482d3bbeec/index.qmd#L27)

The error is 

```
Error in FUN(X[[i]], ...) : 
  Dependency metathis-0d31fe6f 0.1.0 is not disk-based
Calls: .main ... dependencies_from_render -> html_dependencies_as_string -> lapply -> F
```

but I'm not sure if it is b/c of quarto or incorrect usage. Thank you!

**Comment by gadenbuie** [comment]
hmm that's a new one for me too, but yeah it's probably an issue with metathis.

What I think is going on is that metathis uses some edge-case behavior of `htmltools::htmlDependency()` to inject the `<meta>` tags in to the document `<head>` without actually writing any files. I might need to revise this and actually write out an html dependency that could be used with the document.

One thing you can do for now is to write the `meta` object to an `.html` file that you include via the `include-in-header` argument.

````markdown
---
title: "Issue 28"
format: 
  html:
    include-in-header:
      meta.html
editor: visual
---

```{r meta}
#| include: false
library(metathis)
meta() %>%
  meta_name("github-repo" = "https://github.com/shannonpileggi/introducing-gtreg-rmed-2022") %>% 
  meta_social(
    title = "Introducing gtreg: an R package to produce regulatory tables for clinical research",
    url = "https://shannonpileggi.github.io/introducing-gtreg-rmed-2022/#/title-slide",
    image = "https://github.com/shannonpileggi/introducing-gtreg-rmed-2022/blob/main/img/gtreg_overview_preview.PNG?raw=true",
    image_alt = "Flow chart overview of {gtreg} usage and functions.",
    og_type = "slides",
    og_author = "Shannon Pileggi",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@PipingHotdata",
    twitter_site = "@PipingHotdata"
  ) %>% 
  format() %>% 
  writeLines("meta.html")
```
````

**Comment by shannonpileggi** [comment]
Thank you! It rendered without error. The twitter card validator can't render the preview, so we'll see how it comes out when I share in a couple of days!

![image](https://user-images.githubusercontent.com/17747575/186257835-edd34a48-e6c8-4bef-ad35-e055d7ad42e1.png)

**Comment by gadenbuie** [comment]
Ooh, the `include-in-header` key should go under `revealjs`. Sorry, I was testing with a plain html doc.

```patch
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
    chalkboard: true
-  html:
    include-in-header:
      meta.html
```

**Comment by shannonpileggi** [comment]
Thank you! Still not able to read preview, but no more error!

And I did a little tweet & delete test, looked great!

![image](https://user-images.githubusercontent.com/17747575/186294642-1d36eee7-e0d8-46ce-98d6-5e94f2b8596a.png)
